### ISSUE TITLE
[Doc] Add Incubator footer to web pages

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-fury#1258]
https://fury.apache.org/ will need Apache Incubator footers on its pages like https://opendal.apache.org/ has

**Comment by theweipeng** [comment]
> https://fury.apache.org/ will need Apache Incubator footers on its pages like https://opendal.apache.org/ has

Thank you for your reminder. We refactored the page a few days ago, and now it includes the Apache Incubator footers.
