### ISSUE TITLE
[LICENSE] need proper licensing of Preconditions class?

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-fury#1275]
org.apache.fury.util.Preconditions seems to be basically derived from Guava's class.

If so. we need
* to replace the license header with the license header from the original Guava source file
* ideally add a comment with a link to the Guava source file
* update the LICENSE file to acknowledge the Guava license and copyright

I think we need a very good look at https://github.com/apache/incubator-fury/pull/1244 and https://github.com/apache/incubator-fury/pull/1114 to see if there are other source files where we have borrowed from Guava.

**Comment by chaokunyang** [comment]
Hi @pjfanning , thanks for bring this license issue up, I'll take a look later

**Comment by pjfanning** [comment]
I'll close this for now. Updating the project LICENSE/NOTICE can be done later.
