### ISSUE TITLE
[CODE HEADERS] Can we remove the author tags from the Fury code covered by the code grant?

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-fury#1281]
It appears to be unusual to have author tags in ASF code bases. There are exceptions for code that is borrowed from 3rd party sources - if it was not explicitly granted to the ASF.

**Comment by chaokunyang** [comment]
Hi PJ, do you mean the java doc author tag like:
```java
/**
 * Thread safe serializer interface. {@link Fury} is not thread-safe, the implementation of this
 * interface will be thread-safe. And support switch classloader dynamically.
 *
 * @author chaokunyang
 */
```

**Comment by chaokunyang** [comment]
We have such tags before joining ASF. If it's not recommanded, I can create a PR to remove it all

**Comment by pjfanning** [comment]
Yes - it is the `@author` tags is what I am referring to.

The ASF likes the idea of collective code owenership. The git history and git blame give a good idea of authorship anyway.

**Comment by chaokunyang** [comment]
Will be removed in #1282

**Comment by pjfanning** [comment]
https://whimsy.apache.org/board/minutes/Confirming_that_the_current_stance_on__author_tags_as.html

It is a recommendation (strong one) that the tags are removed but the PPMC could decide to allow them, if people are very attached to them.

**Comment by chaokunyang** [comment]
I think tags can be removed. Currently only java code contains `@author`.
