### ISSUE TITLE
Caused by: io.fury.exception.InsecureException: Class java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject isn't in allow list for serialization.

### ISSUE THREAD

**Issue by Maurice-Betzel** [apache/incubator-fury#1293]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

Fury 0.4.1
OS Win11 x64
JDK openJDK 1.8

### Component(s)

Java

### Minimal reproduce step

Serializing org.apache.karaf.cellar.dosgi.RemoteServiceCall containing a LinkedBlockingQueue

`Fury instance = Fury.builder()
                .withLanguage(Language.JAVA)
                .withMetaContextShare(false)
                .withRefTracking(true)
                .withIntCompressed(false)
                .withLongCompressed(false)
                .withStringCompressed(false)
                .withCompatibleMode(CompatibleMode.COMPATIBLE)
                .withClassVersionCheck(false)
                .withJdkClassSerializableCheck(true)
                .withDeserializeUnexistedClass(false)
                .withAsyncCompilation(true)
                .withCodegen(true)
                .ignoreTimeRef(false)
                .registerGuavaTypes(false)
                .requireClassRegistration(false)
                .suppressClassRegistrationWarnings(false)
                .build();`

### What did you expect to see?

As a drop in replacement for the default Java serialization it should support the whole Java JDK per default.

### What did you see instead?

`java.lang.RuntimeException: Serialize object of type class java.util.concurrent.LinkedBlockingQueue failed, Try to use class io.fury.serializer.JavaSerializer instead by fury.registerSerializer(class java.util.concurrent.LinkedBlockingQueue, new JavaSerializer(fury, class java.util.concurrent.LinkedBlockingQueue)) or implement a custom class io.fury.serializer.Serializer.`

`Caused by: io.fury.exception.InsecureException: Class java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject isn't in allow list for serialization. If this class is allowed for serialization, please add it to allow list by AllowListChecker#addAllowClass`

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by Maurice-Betzel** [comment]
Only happens with a AllowListChecker added in STRICT mode

**Comment by chaokunyang** [comment]
Please provide stack using multiple line with indent, it's hard to read to see all stacktrace in one line. You can use markdown \`\`\`\`\`\` syntax for it

**Comment by chaokunyang** [comment]
> If this class is allowed for serialization, please add it to allow list by AllowListChecker#addAllowClass

Like the exception message said: ` If this class is allowed for serialization, please add it to allow list by AllowListChecker#addAllowClass`. You need to add this class by `AllowListChecker#addAllowClass` since you used AllowListChecker added in STRICT mode

**Comment by Maurice-Betzel** [comment]
In my understanding of a drop in replacement it should support all of the default JDK classes including the serializable inner classes.

**Comment by chaokunyang** [comment]
> In my understanding of a drop in replacement it should support all of the default JDK classes including the serializable inner classes.

It does support inner class, you just disabled it by class checker

**Comment by chaokunyang** [comment]
![image](https://github.com/apache/incubator-fury/assets/12445254/6ecd9413-d248-4d44-845d-e630ffc72f49)

**Comment by Maurice-Betzel** [comment]
Interesting, is there a reason for this behaviour of disallowing JDK inner classes in STRICT mode and are there any other implecations?

**Comment by chaokunyang** [comment]
There are many security vulnerabilities in JDK serialization. We won't allow serialize any jdk serializable objects by default.

**Comment by Maurice-Betzel** [comment]
I order to allow all JDK classes add the following to the AllowListChecker whitelist:
`Collection<String> whiteList = new HashSet();`
`whiteList.add("java.*");`
