### ISSUE TITLE
Consider to remove CODEOWNERS

### ISSUE THREAD

**Issue by PragmaTwice** [apache/incubator-fury#1296]
It is outdated and from my view it is unnecessary to keep.

**Comment by chaokunyang** [comment]
Agreed, we can remove it now

**Comment by chaokunyang** [comment]
Projects like apache/arrow still have such configurations:
![image](https://github.com/apache/incubator-fury/assets/12445254/d13e1783-42f2-479f-8cbd-8ea25c2ff9d6)

It may be useful for some new contributors to ask someone for review code

**Comment by PragmaTwice** [comment]
But in the current CODEOWNERS, just one ID [chaokunyang](https://github.com/chaokunyang) is valid, it's useless.

If you want to add, you can add a new version after deleting the current one.

**Comment by liuxiaocs7** [comment]
Hi, @PragmaTwice and @chaokunyang

seems incorrect user id results invalid file

![image](https://github.com/apache/incubator-fury/assets/42756849/8bf168c0-7cd1-4725-b2bb-1bd987acb529)

**Comment by chaokunyang** [comment]
> But in the current CODEOWNERS, just one ID [chaokunyang](https://github.com/chaokunyang) is valid, it's useless.
> 
> If you want to add, you can add a new version after deleting the current one.

It's out-dated, we should update it. I suggest preserving it. If it did not help with code review, then we should remove it.

**Comment by chaokunyang** [comment]
Closed for now, feel free to reopen it if current review mechanism does't meet the community requirements
