### ISSUE TITLE
Update fury.apache.org web website content

### ISSUE THREAD

**Issue by LiangliangSui** [apache/incubator-fury#1300]
Currently, some CSS styles of fury.apache.org are inconsistent and need to be updated.

For example, in the first picture, its content is not centered.
![image](https://github.com/apache/incubator-fury/assets/116876207/64125bea-7036-4cef-b5b0-110b7eadae5f)

The question in the second picture is too obtrusive. The font size and color should be adjusted.
![image](https://github.com/apache/incubator-fury/assets/116876207/e9688c4f-7484-416d-9608-caf3b9403e93)

**How is this website maintained and where is the code?**

**Comment by PragmaTwice** [comment]
> How is this website maintained and where is the code?

https://github.com/apache/incubator-fury-site.

**Comment by theweipeng** [comment]
> Currently, some CSS styles of fury.apache.org are inconsistent and need to be updated.
> 
> For example, in the first picture, its content is not centered. ![image](https://private-user-images.githubusercontent.com/116876207/294069064-64125bea-7036-4cef-b5b0-110b7eadae5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjcyMjAsIm5iZiI6MTcwNDc2NjkyMCwicGF0aCI6Ii8xMTY4NzYyMDcvMjk0MDY5MDY0LTY0MTI1YmVhLTcwMzYtNGNlZi1iNWIwLTExMGI3ZWFkYWU1Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwMjIyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZmNmMzg2YTczODRjYTMxODY5MjFlMGI5OTQzMDhmNzVhNmE1MWY1ZTA0Zjk2MDA3NGQ2MzUyZTE5NmQzYjM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.v0Qaxk98W-47aUvIini_na7QCKodez__1fl8vmolbAs)
> 
> The question in the second picture is too obtrusive. The font size and color should be adjusted. ![image](https://private-user-images.githubusercontent.com/116876207/294069123-e9688c4f-7484-416d-9608-caf3b9403e93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NjcyMjAsIm5iZiI6MTcwNDc2NjkyMCwicGF0aCI6Ii8xMTY4NzYyMDcvMjk0MDY5MTIzLWU5Njg4YzRmLTc0ODQtNDE2ZC05NjA4LWNhZjNiOTQwM2U5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwMjIyMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yODRjYTBkYWM0MzhkMzUwNWFhZDlmMDBhMDUwZTlmYzY2MjRmYTk4ZjBiODRkYjgyMzM2NmMwOTlhNjAwNWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rhNplWnHMkgCCoKwmsUv_gW5KNn03WX2QL36Q_qpCi8)
> 
> **How is this website maintained and where is the code?**
@LiangliangSui 
Hi, Are you already working on a fix for it? If not, I'd like to take it on and contribute a solution.

**Comment by LiangliangSui** [comment]
Is this time acceptable?

**Comment by theweipeng** [comment]
> Is this time acceptable?

Yes, this time is acceptable for me

**Comment by LiangliangSui** [comment]
![image](https://github.com/apache/incubator-fury/assets/116876207/0dad97d3-eaab-4851-a40e-e1d58ade8b98)

The effect is as shown in the picture above. Is this okay? If so, I will submit a PR immediately.

**Comment by chaokunyang** [comment]
Looks good to me

**Comment by theweipeng** [comment]
> ![image](https://github.com/apache/incubator-fury/assets/116876207/0dad97d3-eaab-4851-a40e-e1d58ade8b98)
> 
> 
> 
> The effect is as shown in the picture above. Is this okay? If so, I will submit a PR immediately.

Yes, It is good! could you please take a screenshot on mobile side?

**Comment by LiangliangSui** [comment]
![image](https://github.com/apache/incubator-fury/assets/116876207/a49fabdd-2985-4c56-846e-dda744cbf179)

**Comment by theweipeng** [comment]
> ![image](https://github.com/apache/incubator-fury/assets/116876207/a49fabdd-2985-4c56-846e-dda744cbf179)
> 
> 

Great

**Comment by LiangliangSui** [comment]
Fixed by https://github.com/apache/incubator-fury-site/pull/101
