### ISSUE TITLE
[Feature]  Add PR and issue specification documents

### ISSUE THREAD

**Issue by caicancai** [apache/incubator-fury#1308]
The specifications of issue and PR are the standards that a good community should have. We should explain these specifications to developers. This is conducive to community archiving and developers to learn. I don’t know if such a document already exists.

**Comment by caicancai** [comment]
I have seen some communities leave some historical artifacts due to irregularities in raising PRs and issues. I hope Fury can avoid these.

**Comment by chaokunyang** [comment]
If we update your PR/issue template, will it address this?

**Comment by caicancai** [comment]
> If we update your PR/issue template, will it address this?

No, to completely solve this problem may require one-to-one communication between the memeber and the developer's PR, but this is unfair to the memeber. We can reduce this problem through documents + update your PR/issue template, etc. The occurrence of similar problems, such as adding a check on the PR title in the cli and updating your PR/issue template, etc. This method is very common in some communities. I know that the calcite community is currently more strict about this, but I feel that the calcite community is too strict.

**Comment by caicancai** [comment]
My current thoughts are
1. update our PR/issue template
2. Add check for pr title in cli
3. Add this part of the documentation

**Comment by caicancai** [comment]
@chaokunyang I looked at other projects like calcite, spark, etc. I think it is a good choice to add a PR title check in cli. For example, restrict PR to have keywords: issue number, hotfix, etc. The standards we need to specify are which PRs should be issued and which ones are hotfixes.

**Comment by PragmaTwice** [comment]
For PR titles, we can follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

IMHO designing PR and issue templates is quite challenging. Additionally, I believe that excessive restrictions are not beneficial.

**Comment by caicancai** [comment]
> For PR titles, we can follow the [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).
> 
> IMHO designing PR and issue templates is quite challenging. Additionally, I believe that excessive restrictions are not beneficial.

Thank you for your reply. Yes, how to ensure that there are no excessive restrictions is also a complex issue. Some communities are trying a very strict restriction, and the shortcomings are also very obvious, which may discourage some developers. Perhaps we should think about how to grasp this degree

**Comment by eolivelli** [comment]
Hello,
In my experience it is usually enough to have a good pr/issues template.

We could enforce the PR title to some specific format.

You check it out in apache/pulsar

@tisonkun worked on this topics for the Pulsar community

**Comment by caicancai** [comment]
thank everyone https://github.com/apache/incubator-fury/pull/1317
