### ISSUE TITLE
Rename src to cpp

### ISSUE THREAD

**Issue by LiangliangSui** [apache/incubator-fury#1327]
Can we rename src to cpp so that it can be unified with the existing naming method (such as Java, javascript, python, etc.).

**Comment by chaokunyang** [comment]
Could you spit this into two issues? They are not related. For the first one, I agree with you. I plan to rename to cpp previously but haven't started yet. I will submit an pr later

**Comment by LiangliangSui** [comment]
I can do this work and I would very much like to be involved in this project if you agree.

**Comment by chaokunyang** [comment]
I just created a PR for this, but feel free to submit more PR if you like.
