### ISSUE TITLE
support wasm build

### ISSUE THREAD

**Issue by ouzhou** [apache/incubator-fury#1339]
any plan to support wasm build?

**Comment by chaokunyang** [comment]
Hi @ouzhou , could you elaborate more what needs be done for wasm build? I'm not familiar with this field.

**Comment by ouzhou** [comment]
use wasm in web
@chaokunyang

**Comment by ouzhou** [comment]
emcc  or wasm-pack

**Comment by theweipeng** [comment]
> emcc or wasm-pack

Does your app need to interact with rust？or other languages？

**Comment by ouzhou** [comment]
i just want to call in the browser, but js only support nodejs, so build rust code or c code to wasm, run webassembly in browser

**Comment by theweipeng** [comment]
> i just want to call in the browser, but js only support nodejs, so build rust code or c code to wasm, run webassembly in browser
JavaScript impl supports browsers

**Comment by ouzhou** [comment]
any idea to test performance , compare with webassembly or pure js

**Comment by ouzhou** [comment]
no , not work



> > JavaScript impl supports browsers
![](https://github.com/apache/incubator-fury/assets/7693866/27e681c6-ca75-4a92-84af-80231625bcd7)

**Comment by ouzhou** [comment]
done

**Comment by theweipeng** [comment]
> done
Please feel free to open a issue if you are still running into issues and we would be happy to help troubleshoot further.
