### ISSUE TITLE
[Java] Specify JPMS module names

### ISSUE THREAD

**Issue by mtf90** [apache/incubator-fury#1341]
## Is your feature request related to a problem? Please describe.

When using fury in a modular (JPMS) application, the `maven-compiler-plugin` warns that

```
[WARNING] ****************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [fury-core-0.5.0-SNAPSHOT.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] ****************************************************************************************************************************************************
```

## Describe the solution you'd like

With this feature request I propose to claim and configure module names to get rid of this warning.

I basically see two feasible approaches to achieve this goal:

1. The least invasive approach would be to use the `Automatic-Module-Name` entries in the `MANIFEST.MF`s of the respective `.jar` files. This does not affect the build process in any way and can be configured relatively easy via configurations in the `maven-jar-plugin` (or the `maven-shade-plugin` if you use it).
2. To fully support *named* modules, you would have to provide a full `module-info.java` descriptor. Since this is a Java9+ feature, you would have to extend the build process to either use multiple compile phases (one for `module-info.java` on Java9+ and one for the remaining code on Java8 to maintain backwards compatibility) or build a multi-release JAR. This would make sense if you want to support tools such as `jlink` or `jpackage` in the future. However, this would also require your dependencies to be fully modularized. So if that is not the case, it is probably not worth the effort for now.

## Additional context

I could lend a hand and provide an initial PR for the first solution. The only thing worth discussing beforehand is which module names you want to claim. You could either go with the direct translation of the maven coordinates, e.g. `org.apache.fury.fury_core`, `org.apache.fury.fury_format`, etc. or go with more idiomatic names such as `org.apache.fury.core`, `org.apache.fury.format`, etc.

**Comment by chaokunyang** [comment]
Hi @mtf90 , thanks for bringing up this. I think we can go with first solution first. Some dependency such as arrow used by fury-format hasn't released support for JPMS. It's supported in main branch: https://github.com/apache/arrow/blob/main/java/memory/memory-core/src/main/java/module-info.java, but not released yet.

And `org.apache.fury.core`, `org.apache.fury.format` looks good to me. Would you like to create a pr for this?

In the long run, I think Fury should support JPMS fully. One thing I'm not sure whether it affect java8 users. Fury will support java8 for a long time, the support for JPMS should not break the support for java8

**Comment by mtf90** [comment]
Dear @chaokunyang, I created a PR. Feel free to change the module names for the test modules. I went with a hierarchical naming convention since you seem to prefer the `org.apache.fury.core` approach.


Maybe I can share some experience for adding full JPMS support in the future since I'm in a similar situation with @LearnLib at the moment (which is why I encountered the missing module names of Fury in the first place).

We went with the two-compilation-phase approach which
* compiles everything to Java 9 in order to use the compiler's built-in checks for sound `module-info.java` definitions and then
* re-compile everything but the `module-info.java` file to Java 8.

This allows us to keep the `module-info.java` file alongside the actual code and profit off of the IDE's support for modules. The main disadvantage is that a Java 9+ compiled class is now alongside the other `.class` files in the built `.jar` file. However, since `module-info` is not a valid Java identifier, you cannot reference this class directly in regular applications. Only (Java 8) code that deliberately scans the contents of a `.jar` file may run into `UnsupportedClassVersionError`s

An alternative would be to keep the `module-info.java` in a separate source directory (something like `src/main/java9`) and construct a multi-release JAR by compiling (only) the `module-info.java` descriptor to the the `META-INF/versions/9` directory of the `.jar` file (which is what, e.g., `slf4j` does). The main disadvantage I see with this approach is (besides the wonky IDE support) that the multi-release semantics are defined only on the `.jar` level. However, with maven, your typical lifecycle is `compile` -> `test` -> `package` so you would need to move certain (unit-) tests to the `integration-test` phase in order to test your module definitions (such as service definitions via `uses` and `provides`).

**Comment by chaokunyang** [comment]
Hi @mtf90 , thanks for submitting the PR #1343 , the naming looks good to me.

And thanks for detailed explaination for JMPS solution too, I can see a feasible path top JPMS now. Fury currently dependends on guava, which doesn't support JPMS https://github.com/google/guava/issues/2970. We may need to hold this until guava support it or we remove guava dependencies.
