### ISSUE TITLE
Fury:Java create a Maven / Gradle plugin for build time compiling and packaging

### ISSUE THREAD

**Issue by Maurice-Betzel** [apache/incubator-fury#1351]
## Describe the solution you'd like
Create the serde classes beforehand avoiding runtime penalties.

**Comment by chaokunyang** [comment]
We can implement an annotation processor to generate code at build time, I think that can solve this issue

**Comment by Maurice-Betzel** [comment]
> We can implement an annotation processor to generate code at build time, I think that can solve this issue

So the annotation is added to the class in question needing a serde class? How to annotate plain Java exceptions or third party classes?  In this case it also adds an extra Fury dependency on those classes. With a Maven plugin I could just add what I want to the plug-ins configuration no matter what origin of the class. I always try to avoid those annotations because then I must install and maintain the lib providing them on remote runtimes not using Fury instances as well.

**Comment by chaokunyang** [comment]
You can write an empty class, and annotate it to generate serializers for  other classes. Both annotation processor and maven plugin are executed at compile time, it doesn't introduce extra runtime dependencies.

**Comment by Maurice-Betzel** [comment]
Empty classes and Lombok, both stuff I do not like. I will create a simple first version.

**Comment by Maurice-Betzel** [comment]
Empty classes and Lombok, both stuff I do not like. I will create a simple first version.
