### ISSUE TITLE
[Java] Performance compared with JdkSerializationRedisSerializer

### ISSUE THREAD

**Issue by liudaac** [apache/incubator-fury#1362]
MyCode

[public class FuryRedisSerializer implements RedisSerializer<Object> {

	private ThreadSafeFury fury = Fury.builder()
			  .withLanguage(Language.JAVA)
			  .withRefTracking(false)
			  .withCompatibleMode(CompatibleMode.SCHEMA_CONSISTENT)
			  .withAsyncCompilation(true)
			  .requireClassRegistration(false)
			  .buildThreadSafeFury();
	
	@Override
	public byte[] serialize(Object value) throws SerializationException {
		// TODO Auto-generated method stub
		byte[] bytes = fury.serialize(value);
		return bytes;
	}

	@Override
	public Object deserialize(byte[] bytes) throws SerializationException {
		// TODO Auto-generated method stub
		return fury.deserialize(bytes);
	}
	
	@SuppressWarnings("rawtypes")
	public static void main(String[] args) {
		String test = "wqweqweqewqeqweqweqeqweqweqweqwe";
		FuryRedisSerializer serializer = new FuryRedisSerializer();
		long start1 = System.currentTimeMillis();
		byte[] datas = serializer.serialize(test);
		String out1 = (String)serializer.deserialize(datas);
		long end1 = System.currentTimeMillis();
		
                System.out.println(out1 + "    "+(end1 - start1));
		
		JdkSerializationRedisSerializer jdkSerializer = new JdkSerializationRedisSerializer();
		long start2 = System.currentTimeMillis();
		byte[] datas2 = jdkSerializer.serialize(test);
		String out2 = (String)jdkSerializer.deserialize(datas2);
		long end2 = System.currentTimeMillis();
		
                System.out.println(out2 + "    "+(end2 - start2));
		
		HttpError httpError = HttpError.instance(AradinCodedEnum.OK, test);
		start1 = System.currentTimeMillis();
		datas = serializer.serialize(httpError);
		HttpError httpError1 = (HttpError)serializer.deserialize(datas);
		end1 = System.currentTimeMillis();
		
		System.out.println(httpError1.getCoded() + "    "+(end1 - start1));
		
		start2 = System.currentTimeMillis();
		datas2 = jdkSerializer.serialize(httpError);
		HttpError httpError2 = (HttpError)jdkSerializer.deserialize(datas2);
		end2 = System.currentTimeMillis();

		System.out.println(httpError2.getCoded() + "    "+(end2 - start2));
	}
}](https://github.com/liudaac/aradin/blob/main/aradin-spring/aradin-spring-redis-starter/src/main/java/cn/aradin/spring/redis/starter/serializer/FuryRedisSerializer.java)

The main method`s output is below

wqweqweqewqeqweqweqeqweqweqweqwe    2
wqweqweqewqeqweqweqeqweqweqweqwe    4
OK    44
OK    1

So does fury really improve performance like your benchmark-show?

**Comment by chaokunyang** [comment]
@liudaac You need to warm up before collecting metrics, and execute many times for compute timing. I suggest to use jmh tools for such benchmark

**Comment by liudaac** [comment]
I tested it according to the way you said, excluding the first time, and indeed the subsequent performance is better. Thanks.

**Comment by chaokunyang** [comment]
Fury will generate code at the first time, the codegen is slow
