### ISSUE TITLE
[Java] Unable to find Serilizer.java interface as present in java graph guide

### ISSUE THREAD

**Issue by aarvy-9** [apache/incubator-fury#1367]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

Fury - 0.4.1

### Component(s)

Java

### Minimal reproduce step

https://github.com/apache/incubator-fury/blob/ea9602f9425002d633569381c5dc7986706759bb/docs/guide/java_object_graph_guide.md#implement-a-customized-serializer

### What did you expect to see?

Expect to implement customized serializer

### What did you see instead?

Unable to find Serilizer interface as shown in 
https://github.com/apache/incubator-fury/blob/ea9602f9425002d633569381c5dc7986706759bb/docs/guide/java_object_graph_guide.md#implement-a-customized-serializer

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Hi @aarvy-9 , thanks for reporting this issue. `org.apache.fury.serializer.Serializer` is an abstract class,  this is an error in uour doc. Could you try `class FooSerializer extends Serializer<Foo>`?

**Comment by aarvy-9** [comment]
Sure...the class we want to serialize constantly evolves and I want to make sure all developers register newly added class with fury. Apart from Serializer abstract class, is there any interface that we can implement?

**Comment by chaokunyang** [comment]
You can configure Fury with `FuryBuilder#requireClassRegistration(true)` and register every class by `Fury#register` manually
