### ISSUE TITLE
[Java] Advice on Java Fury inheritance structure

### ISSUE THREAD

**Issue by LiangliangSui** [apache/incubator-fury#1374]
The current inheritance structure of `ThreadLocalFury / AbstractThreadSafeFury / ThreadSafeFury / Fury` is as follows

![image-20240219100956126](https://github.com/apache/incubator-fury/assets/116876207/31f3aa51-ad9e-443c-83e6-8bd49dcfda8f)

`ThreadSafeFury` and `Fury` are independent of each other, but they also have the same methods. Therefore, is it possible to abstract an interface (named `AbstractFury`), make `Fury` and `ThreadSafeFury` implement` AbstractFury`, and then move the same methods in `Fury` and `ThreadSafeFury` to `AbstractFury`, thus making the entire Fury-related class inheritance system look more complete and clear. 

The adjusted inheritance structure is as follows

![image-20240219101407316](https://github.com/apache/incubator-fury/assets/116876207/b4dfc83f-0189-4b08-a764-5b77fa14a2eb)

**Comment by chaokunyang** [comment]
Good suggestion! The same methods should be abstracted into an interface.

**Comment by LiangliangSui** [comment]
I will submit a PR to do this.

**Comment by chaokunyang** [comment]
One concern is about how we name this interface to make it more intuitive for use. `AbstractFury` is used for abstract class instead fo interface. I don't find a better naming, naming is always hard.

The naming should have `Fury` included and not introduce more confusion.

FYI, In scala, we use `Trait` for such cases, like `FuryTrait`, but trait is not used requently in java. `FuryBase/BaseFury` has similar issue as `AbstractFury`

**Comment by chaokunyang** [comment]
`BaseFury` looks good to me too

**Comment by LiangliangSui** [comment]
https://github.com/apache/incubator-fury/pull/1382
