### ISSUE TITLE
[Rust] Corrections for Installation and #[derive()] possibilities

### ISSUE THREAD

**Issue by ArmDaniel** [apache/incubator-fury#1384]
## Is your feature request related to a problem? Please describe.
In the Rust example, right on the Installation procedures, it is marked that a crate called fury_derive should be installed. However, the correct name is "fury-derive", otherwise the installation will fail. Also, it points to the same repo as the 'fury' crate. I don't think that is intended? Also, the issue for fury-derive, since it points to the same repo, is that it that does not allow access to the elements specified in the user guide, namely: "FuryMeta, Deserialize, Serialize". However, it seems that simply having:
`use fury::{from_buffer, to_buffer, Fury}`
 is enough to do the job.

## Describe the solution you'd like
Remove the "fury-derive" crate unless it serves a specific purpose. Add the correct usage of the "fury" crate in the user guide.

**Comment by ArmDaniel** [comment]
After further experimentation and playing around, I have that the "Serialize", "Deserialize" and "FuryMeta" traits can indeed be found, but only with :
`use fury::__derive::{Serialize, Deserialize, FuryMeta};`

This should be reflected in the user guide.

**Comment by theweipeng** [comment]
> ## Is your feature request related to a problem? Please describe.
> In the Rust example, right on the Installation procedures, it is marked that a crate called fury_derive should be installed. However, the correct name is "fury-derive", otherwise the installation will fail. Also, it points to the same repo as the 'fury' crate. I don't think that is intended? Also, the issue for fury-derive, since it points to the same repo, is that it that does not allow access to the elements specified in the user guide, namely: "FuryMeta, Deserialize, Serialize". However, it seems that simply having: `use fury::{from_buffer, to_buffer, Fury}` is enough to do the job.
> 
> ## Describe the solution you'd like
> Remove the "fury-derive" crate unless it serves a specific purpose. Add the correct usage of the "fury" crate in the user guide.

Thank you for submitting the issue!  The usage in guide is outdated, using `use fury::{from_buffer, to_buffer, Fury}` is enough to do the job. I will update the guide in a another PR.

**Comment by theweipeng** [comment]
> It should also be noted in the use guide that, for Rust, you must use the following command: `crate add fury` since fury is a library crate. Attempting to cargo install will fail as it has no binaries.

The Xlang protocol is not stable yet, and there is still much work to be done before the first release version is ready. Once fury-rust becomes stable, it will be integrated with Cargo
