### ISSUE TITLE
[Java] Suggested technique for Serializers to handle primitive arrays?

### ISSUE THREAD

**Issue by tommyettinger** [apache/incubator-fury#1405]
## Is your feature request related to a problem? Please describe.
It seems somewhat odd that `MemoryBuffer` provides `readLongsWithSizeEmbedded()` for `long[]`, as well as versions for `byte[]` and `char[]`, but nothing for other primitive arrays. Is there some recommended way for `Serializer`s to handle things like `int[]` written by `writePrimitiveArrayWithSizeEmbedded()` already?

## Describe the solution you'd like
I have implemented [my own versions](https://github.com/tommyettinger/tantrum/blob/main/tantrum-jdkgdxds/src/main/java/com/github/tommyettinger/tantrum/jdkgdxds/helpers/Support.java) of array-reading methods, I just don't know if I'm missing an existing solution that wouldn't require so many copies of Fury code.

## Additional context
I had a hard time finding examples of custom `Serializer`s in the documentation or even the tests. I think I am doing things correctly, but I'm not sure.

**Comment by chaokunyang** [comment]
Hi @tommyettinger , I'm glad to see that you extend Fury for more use cases. Our user doc is not good enough, sorry for this.

If you want to handle other primitive arrays ,you can take https://github.com/apache/incubator-fury/blob/5aba0c8780fb7fdff96a63ec60cde631eb107cb7/java/fury-core/src/main/java/org/apache/fury/serializer/ArraySerializers.java#L418 for an example

**Comment by tommyettinger** [comment]
Oh, that's much simpler than I thought! Thanks! It makes sense that arrays, being reference types, could be serialized like other reference types; I just didn't know there was a serializer already registered. Would it make sense for there to be a listing somewhere of which types have serializers already registered? Even a link to source code where existing types are all shown would be plenty. I know `String` doesn't need to be registered, for example, but I don't know if `String[]` needs to be registered.

**Comment by chaokunyang** [comment]
All registered serializers are lied at `fury-core/src/main/java/org/apache/fury/serializer`. `String[]` are registered too. It's a good suggestion to point out which serializers has been registered. Maybe we can add a link to the source code in the java serialization guide. List serializers sounds good too.

FYI, serializers for `String[]` has been registered in `org.apache.fury.serializer.ArraySerializers.StringArraySerializer`

**Comment by tommyettinger** [comment]
That sounds good to me! I'll close this now.
