### ISSUE TITLE
[Java] register enables check behavior by default

### ISSUE THREAD

**Issue by LiangliangSui** [apache/incubator-fury#1407]
Can we delete the `ClassResolver#registerWithCheck` interface and only keep the `register` interface. The `register` interface carries the check function by default, which always prevents repeated registration, and repeated registration throws an exception.

Now, if you use the `register` interface to repeatedly register a Class, nothing will happen, no exception will be thrown, and the registration will not be successful.

**Comment by chaokunyang** [comment]
Yep, `registerWithCheck` seems unnecessary, maybe we should remove it

**Comment by LiangliangSui** [comment]
https://github.com/apache/incubator-fury/pull/1424 has been merged.
