### ISSUE TITLE
rename blacklist code

### ISSUE THREAD

**Issue by pjfanning** [apache/incubator-fury#1447]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

n/a

### Component(s)

Other

### Minimal reproduce step

n/a

### What did you expect to see?

Blacklist has taken on negative connotations. In the modern era, many people don't want to associate colours with connotations of good or bad. Likewise, whitelist is unpopular now.

Could we rename these files are disallow or disallow-list or something like that?

### What did you see instead?

n/a

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
Good catch, I think we can rename it to disallow-list or forbidden-list
