### ISSUE TITLE
[Java] Does Fury preregister common Java collection classes, or do I need to register them manually?

### ISSUE THREAD

**Issue by cdxf** [apache/incubator-fury#1456]
I would like to know if Fury automatically handles the registration of these common Java collection classes: ```ArrayList```, ```HashMap``` or classes that are not part of the public API (which I can't access directly), like: ```ImmutableCollections.Map1```, ```ImmutableCollections.List12```, ```ImmutableCollections.ListN```...

Or if I need to explicitly register them myself when using Fury?

And what about Interface class, do I need to register the Interface class also (for example ```List.class```)

**Comment by chaokunyang** [comment]
They are all registered by fury, you can access ClassResolver first a detailed registered list

**Comment by LiangliangSui** [comment]
@cdxf Details can be viewed at https://github.com/apache/incubator-fury/blob/main/java/fury-core/src/main/java/org/apache/fury/resolver/ClassResolver.java#L262

**Comment by LiangliangSui** [comment]
Should we indicate in https://github.com/apache/incubator-fury/blob/main/docs/guide/java_object_graph_guide.md which classes have been registered and which Serializers have been registered? Currently these things are in the documentation It's rather vague. @chaokunyang

**Comment by chaokunyang** [comment]
@LiangliangSui Yes, we'd better document those classes in our doc
