### ISSUE TITLE
[Java] optimize MemoryBuffer.unsafeWritePositiveVarLong bytecode size

### ISSUE THREAD

**Issue by chaokunyang** [apache/incubator-fury#1465]
## Is your feature request related to a problem? Please describe.
The bytecode size of `MemoryBuffer.unsafeWritePositiveVarLong` is 466 bytes, which is too big for jvm jit inline.

![image](https://github.com/apache/incubator-fury/assets/12445254/9204e795-b33a-46e8-af8c-b2ffb141f5a7)

## Describe the solution you'd like
We can rewrite it using algorithms like I used in #1463

**Comment by wangjie-fourth** [comment]
@chaokunyang it is done. maybe need close this issue?
