### ISSUE TITLE
[Java] Optimize ClassResolver#register bytecode size

### ISSUE THREAD

**Issue by LiangliangSui** [apache/incubator-fury#1482]
## Is your feature request related to a problem? Please describe.
`ClassResolver#register` bytecode size is 341 bytes，hot method too big
![image](https://github.com/apache/incubator-fury/assets/116876207/f9828d94-01e2-4104-ae4f-c3602e4e00d0)

## Describe the solution you'd like
Reduce `ClassResolver#register` bytecode size so that `ClassResolver#register` hot method can still be inlined.

**Comment by chaokunyang** [comment]
The registration is only executed for Fury init. It's not on the critical path. Do we need to optimize this?

**Comment by chaokunyang** [comment]
@LiangliangSui You can also use async-profiler to cpature a flame graph to identify the most time-consuming part

**Comment by chaokunyang** [comment]
@LiangliangSui do we have any updates on this?

**Comment by LiangliangSui** [comment]
I extracted a piece of logic that is not executed frequently into a function to reduce the bytecode size of the register method. The extracted function is as follows:

```java
  public void register(Class<?> cls, int classId) {
    ......

    short id = (short) classId;
    if (id < registeredId2ClassInfo.length && registeredId2ClassInfo[id] != null) {
      throw new IllegalArgumentException(
          String.format(
              "Class %s with id %s has been registered, registering class %s with same id are not allowed.",
              registeredId2ClassInfo[id].getCls(), id, cls.getName()));
    }
    extRegistry.registeredClassIdMap.put(cls, id);
    if (registeredId2ClassInfo.length <= id) {
      ensure(id);
    }
    ......
  }

  private void ensure(short id) {
    ClassInfo[] tmp = new ClassInfo[(id + 1) * 2];
    System.arraycopy(registeredId2ClassInfo, 0, tmp, 0, registeredId2ClassInfo.length);
    registeredId2ClassInfo = tmp;
  }

```

Then the `register` function bytecode is reduced from 341 to 314, which is lower than `-XX:+FreqInlineSize(325)`, and is successfully inlined.

![image](https://github.com/apache/incubator-fury/assets/116876207/02e2c438-90bb-4b7c-a523-76a83b944727)

I will upload a PR later to do this.

**Comment by chaokunyang** [comment]
The Fury creation is not frequent, the Jvm compiler is still in c1 stage. The inline threshold is 34 byte in such cases.

**Comment by chaokunyang** [comment]
Is this the most timeconsuming part of Fury creation?

**Comment by LiangliangSui** [comment]
> The Fury creation is not frequent, the Jvm compiler is still in c1 stage. The inline threshold is 34 byte in such cases.

What we can optimize is that when `register` becomes a hot method, it cannot be inlined because its bytecode is larger than `-XX:+FreqInlineSize(325)`.

`-XX:+MaxInlineSize(35)` should be the maximum limit that can be inlined before `register` becomes a hotspot method.

**Comment by LiangliangSui** [comment]
> Is this the most timeconsuming part of Fury creation?

During the Fury creation process, the most time-consuming thing should be the `org.apache.fury.resolver.ClassResolver#addDefaultSerializers` function, not the `register` function.

![image](https://github.com/apache/incubator-fury/assets/116876207/2b525678-cf3d-4294-bbea-76985685a122)

**Comment by LiangliangSui** [comment]
We have optimized `register` in https://github.com/apache/incubator-fury/issues/1510, but I think by reducing the generated bytecode size the same can be done by inlining `register` when it becomes a hot method. Also useful for `register`.
@chaokunyang WDYT?

**Comment by chaokunyang** [comment]
The thing is that it should not be a hot method. If it does, it means users created lots of Fury, which is not allowed.

**Comment by chaokunyang** [comment]
After I optimized register in https://github.com/apache/incubator-fury/issues/1510 , I found Map.put is hte bottleneck now Maybe we should optimize that first.

**Comment by chaokunyang** [comment]
@LiangliangSui I will start the work of meta string in https://fury.apache.org/docs/specification/fury_xlang_serialization_spec/#meta-string to reduce classname serialization space cost before we make release for #1389 . If you'd like to optimize FUry creation, I think maybe we can go that way to optimize the most time-consuming part first

**Comment by LiangliangSui** [comment]
> The thing is that it should not be a hot method. If it does, it means users created lots of Fury, which is not allowed.

Got it.

**Comment by LiangliangSui** [comment]
> @LiangliangSui I will start the work of meta string in https://fury.apache.org/docs/specification/fury_xlang_serialization_spec/#meta-string to reduce classname serialization space cost before we make release for #1389 . If you'd like to optimize FUry creation, I think maybe we can go that way to optimize the most time-consuming part first

That's really cool, I'd be very interested in doing it and learning from you at the same time.
