### ISSUE TITLE
[Discuss][License] do wen need to move license content from NOTICE to LICENSE file

### ISSUE THREAD

**Issue by chaokunyang** [apache/incubator-fury#1498]
## Is your feature request related to a problem? Please describe.
Fury borrowed some code from spark/guava/v8/etc. Currently we add the license of those project in NOTICE file. 

Projects [flink](https://github.com/apache/opendal/blob/master/NOTICE)/[pytorch](https://github.com/pytorch/pytorch/blob/main/NOTICE)  use this method. 

Other projects  such as [spark](https://github.com/apache/spark/blob/master/LICENSE)/[arrow](https://github.com/apache/arrow/blob/main/LICENSE.txt)/etc all put license into `LICENSE` file.

Both ways look good to me, @tisonkun @pjfanning do you have any suggestions?

## Additional context
#1440

**Comment by pjfanning** [comment]
It is my understanding that 3rd party licenses should be mentioned in our LICENSE and notices in those 3rd party projects should be mentioned in our NOTICE file. Not every Apache project seems to do this - so I could be wrong. It might be better to ask this on the general@incubator.apache.org list or something like the ASF legal-discuss mailing list.

**Comment by chaokunyang** [comment]
> It is my understanding that 3rd party licenses should be mentioned in our LICENSE and notices in those 3rd party projects should be mentioned in our NOTICE file. Not every Apache project seems to do this - so I could be wrong. It might be better to ask this on the [general@incubator.apache.org](mailto:general@incubator.apache.org) list or something like the ASF legal-discuss mailing list.

It's my understanding too. Maybe both are legal, but mention 3rd party license in our license and mention notice in our notice reduce the confusion to people since its more intuitive
