### ISSUE TITLE
[Java] Optimize Fury creation speed

### ISSUE THREAD

**Issue by chaokunyang** [apache/incubator-fury#1510]
## Is your feature request related to a problem? Please describe.
Current fury creation takes about 2 millseconds, which is slow, we need to optimize it.

A profiler shows that Fury creation is slow at ClassResolver:
![image](https://github.com/apache/incubator-fury/assets/12445254/b172b34a-6d30-4c1d-a0b7-9d57a74512ed)
![image](https://github.com/apache/incubator-fury/assets/12445254/19c7e30f-1f02-4878-83e3-84aea9a8eeb5)

## Describe the solution you'd like
Avoid String generation, and reduce map resize cost by creating a map with bigger size

## Additional context
#1482

**Comment by LiangliangSui** [comment]
`String#format` takes up most of the time in `register`. Maybe we can use if judgment instead of using `Preconditions#checkArgument`.

**Comment by chaokunyang** [comment]
> `String#format` takes up most of the time in `register`. Maybe we can use if judgment instead of using `Preconditions#checkArgument`.

Preconditions support string template, which can avoid this cost.

**Comment by LiangliangSui** [comment]
> > `String#format` takes up most of the time in `register`. Maybe we can use if judgment instead of using `Preconditions#checkArgument`.
> 
> Preconditions support string template, which can avoid this cost.

Using `if` can reduce unnecessary `HashMap#get` costs.

**Comment by LiangliangSui** [comment]
In addition, is it necessary to output the INFO Log in the [Fury constructor](https://github.com/apache/incubator-fury/blob/main/java/fury-core/src/main/java/org/apache/fury/Fury.java#L143)? I think it is more like a debug log. It was also very time consuming during the creation of Fury.

![image](https://github.com/apache/incubator-fury/assets/116876207/9ea938c7-6fca-401d-b436-0e4ef94819a0)

**Comment by LiangliangSui** [comment]
When we use `FuryLogger` to output logs, the operation of obtaining the line number is the most expensive.

This cost should be unavoidable. Do you have any good suggestions for this cost?

**Comment by chaokunyang** [comment]
> In addition, is it necessary to output the INFO Log in the [Fury constructor](https://github.com/apache/incubator-fury/blob/main/java/fury-core/src/main/java/org/apache/fury/Fury.java#L143)? I think it is more like a debug log. It was also very time consuming during the creation of Fury.
> 
> ![image](https://private-user-images.githubusercontent.com/116876207/322250648-9ea938c7-6fca-401d-b436-0e4ef94819a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwNzkyMzAsIm5iZiI6MTcxMzA3ODkzMCwicGF0aCI6Ii8xMTY4NzYyMDcvMzIyMjUwNjQ4LTllYTkzOGM3LTZmY2EtNDAxZC1iNDM2LTBlNGVmOTQ4MTlhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNFQwNzE1MzBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDg0ZjQ5MDhlNDExYWU0ZDU2OWIxNmRmY2RmODYzNDFhZjA0ZDFhZGE4NDYyZjQ2ZjdkZDNlZWM2NjBjZDc2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-oaBGJ51lGEkWlsDT9-UxbMtmFHM2IHQ34pI0rFZXKo)

We dont' allow users to create fur every frequently, users should create fury and cache it. This log is used to remind him that he is creating fury frequently

**Comment by chaokunyang** [comment]
> When we use `FuryLogger` to output logs, the operation of obtaining the line number is the most expensive.
> 
> This cost should be unavoidable. Do you have any good suggestions for this cost?

You may need to deep into log4j to see how it handlle this. There may have some thread safe cache in their implementation
