### ISSUE TITLE
[Java] Performance issue when deserializing from FuryInputStream with ZstdInputStream

### ISSUE THREAD

**Issue by yihwang6** [apache/incubator-fury#1548]
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-fury/issues) and found no similar issues.

### Version

Version: 0.5.0-SNAPSHOT
OS: Windows
JDK: 8
CommitId：bb419ddf8d4983f438e4b1527c7cb9da74477022

### Component(s)

Java

### Minimal reproduce step

    public static final Fury FURY_RELEASE = Fury.builder()
        .withLanguage(Language.JAVA)
        .requireClassRegistration(false)
        .build();

    public static <T> ByteArrayOutputStream zstdFurySerialize_Release(T origin) {
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
             ZstdOutputStream zstdOutputStream = new ZstdOutputStream(outputStream)) {
            FURY_RELEASE.serializeJavaObject(zstdOutputStream, origin);
            return outputStream;
        } catch (Exception e) {
            System.out.println(e);
            return null;
        }
    }

    public static <T> T zstdFuryDeserialize_Release(ByteArrayInputStream inputStream, Class<T> clazz) {
        try (ZstdInputStream zstdInputStream = new ZstdInputStream(inputStream)) {
            return FURY_RELEASE.deserializeJavaObject(zstdInputStream, clazz);
        } catch (Exception e) {
            System.out.println(e);
            return null;
        }
    }

    public static final org.apache.fury.Fury FURY_SNAPSHOT = org.apache.fury.Fury.builder()
        .withLanguage(org.apache.fury.config.Language.JAVA)
        .requireClassRegistration(false)
        .build();

    public static <T> ByteArrayOutputStream zstdFurySerialize_Snapshot(T origin) {
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
             ZstdOutputStream zstdOutputStream = new ZstdOutputStream(outputStream)) {
            FURY_SNAPSHOT.serializeJavaObject(zstdOutputStream, origin);
            return outputStream;
        } catch (Exception e) {
            System.out.println(e);
            return null;
        }
    }

    public static <T> T zstdFuryDeserialize_Snapshot(ByteArrayInputStream inputStream, Class<T> clazz) {
        try (ZstdInputStream zstdInputStream = new ZstdInputStream(inputStream);
             FuryInputStream furyInputStream = new FuryInputStream(zstdInputStream)) {
            return FURY_SNAPSHOT.deserializeJavaObject(furyInputStream, clazz);
        } catch (Exception e) {
            System.out.println(e);
            return null;
        }
    }

### What did you expect to see?

I tested Fury with zstd and found that using FuryInputStream as input for deserializeJavaObject(...) in the latest snapshot version 0.5.0-SNAPSHOT resulted in significantly lower performance compared to the release version 0.4.0.. 

### What did you see instead?

![image](https://github.com/apache/incubator-fury/assets/139317744/ea00189b-4a07-46a3-bf5b-b0e81afbd90a)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR!

**Comment by chaokunyang** [comment]
I can't run this script on mac, is there somethign extra to configure?

**Comment by chaokunyang** [comment]
How big is your data? Could you add a flamegraph here?

**Comment by chaokunyang** [comment]
The `com.github.luben.zstd.ZstdInputStreamNoFinalizer#available` return `1` instead of actual available data, which make the read slow.

I do think it should return acutal available data:
```java

  public synchronized int available() throws IOException {
    if (this.isClosed) {
      throw new IOException("Stream closed");
    } else {
      return !this.needRead ? 1 : this.in.available();
    }
  }
```

**Comment by chaokunyang** [comment]
Hi @yihwang6 , could you use this https://github.com/apache/incubator-fury/pull/1551 to rerun your benchmark?
