### ISSUE TITLE
Upgrade dubbo-serialization-fury fury-core dependency to 0.5.0

### ISSUE THREAD

**Issue by huisman6** [apache/incubator-fury#1610]
We are going to adopt fury as the default implementation of Dubbo serialization in the production environment, and expect to upgrade [dubbo-serialization-fury](https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-serialization-extensions/dubbo-serialization-fury) dependency fury-core to 0.5.0. Starting from 0.5.x, the Java package name has been adjusted from io.fury to org.apache.fury, which can be considered stable.

Is there any upgrade plan recently? We expect to start testing in June this year. If there is not enough time, I will use the lower version first.

Thanks.

**Comment by chaokunyang** [comment]
We plan to upgrade [dubbo-serialization-fury](https://github.com/apache/dubbo-spi-extensions/tree/master/dubbo-serialization-extensions/dubbo-serialization-fury) next weeks.

The 0.5.0 is just released, we'd like to get some feedbacks before upgrading downstream frameworks

**Comment by huisman6** [comment]
Got it . We should have enough time to wait for the new version to be released.
