### ISSUE TITLE
[Rust] About Enum Naming 

### ISSUE THREAD

**Issue by Xuanwo** [apache/incubator-fury#1676]
## Is your feature request related to a problem? Please describe.

Our current rust naming doesn't fit well with most rust projects.

https://github.com/apache/incubator-fury/blob/31d37f9cf2021899f3dc2f1b06d5b45e79099251/rust/fury/src/types.rs#L156-L183

Clippy will complain about:

```shell
error: name `JAVASCRIPT` contains a capitalized acronym
   --> fury/src/types.rs:254:5
    |
254 |     JAVASCRIPT = 5,
    |     ^^^^^^^^^^ help: consider making the acronym lowercase, except the initial letter: `Javascript`
    |
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#upper_case_acronyms
```

Do those names align with our protocol? Can we change them for better clarity?

## Describe the solution you'd like

Update namings to make rust clippy happy.

## Additional context

None.

**Comment by chaokunyang** [comment]
Our protocol doesn't enforce name convention for enum names. I think we should align with rust name conventions.

How do you think? @theweipeng

**Comment by theweipeng** [comment]
> Our protocol doesn't enforce name convention for enum names. I think we should align with rust name conventions.
> 
> 
> 
> How do you think? @theweipeng 

Yes, the language enum just flags the language in the protocol. Currently, Rust is just compatible with xlang. We should align with rust name conventions.

**Comment by Xuanwo** [comment]
Great, seems we have reached consensus. Please assign this issue to me. I'm willing to help address this.
