### ISSUE TITLE
How about donation to Apache foundation?

### ISSUE THREAD

**Issue by ghost** [apache/incubator-fury#721]
How about donation this project to Apache foundation?
Like apache doubbo, it is long live for long times.

I did not trust alibaba and alipay, but i trust Apache

**Comment by chaokunyang** [comment]
@cnmade It's a good suggestion to let the foundation  to govern the development of fury.  Apache foundation is one of the most mature and biggest open-source foundation in the world. It made so many incredible contributions to the world. 
`The Apache Way` has inspired so many engineers. Its `community over the code`,  opennesss, neutrality and collaboration principles are also what fury try to keep up with. With the help of the foundation, I believe fury can grow much better and faster. 
But fury is just open-sourced in less a week, we are in the early stage, there are still many things for our document/specification/community to build. We need to make our development and governance standardized,  get more contributors involved in, to make fury as a community-driven project. Those things must be finished first.

**Comment by chaokunyang** [comment]
Close this issue since Fury has been donated to ASF
